name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 4 * * *' # Runs every day at 04:00
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to and medium posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://dev.to/feed/ashleymavericks,https://medium.com/feed/@ashleymavericks"
