import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

// Import global CSS files
import '../styles/App.css';
import '../styles/index.css';
import '../styles/portioStyles.css';

// Import CSS from css directory
import '../styles/css/animate.css';
import '../styles/css/animate.min.css';
import '../styles/css/themify-icons.css';
import '../styles/css/BackgroundVideo.module.css';

// Import main SCSS files
import '../styles/sass/style.scss';
import '../styles/sass/style.css';

// Import base SCSS
import '../styles/sass/base/_base.scss';

// Import helpers
import '../styles/sass/helpers/_variables.scss';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}

