import { portfolioItem } from '../types';
import {
  graphQl,
  js,
  mui,
  nextJs,
  reactJs,
  redux,
  restfulApi,
  sass,
  styledComponent,
  tailwindCss,
  typeScript,
} from './skillLists';

export const portfolioArr: portfolioItem[] = [
  {
    portfolioTitle: 'WithJoy',
    img: [
      '/portfolio/withjoy/portfolio-01.jpg',
      '/portfolio/withjoy/portfolio-02.jpg',
      '/portfolio/withjoy/portfolio-03.jpg',
    ],
    description: '',
    usedTechs: [
      nextJs,
      tailwindCss,
      'react spring',
      'zustand',
      'stripe',
      typeScript,
      graphQl,
      reactJs,
      js,
    ],
  },
  {
    portfolioTitle: 'Uptechunt',
    img: [
      '/portfolio/uptechunt/portfolio-02.jpg',
      '/portfolio/uptechunt/portfolio-01.jpg',
      '/portfolio/uptechunt/portfolio-03.jpg',
    ],
    description: '',
    usedTechs: [
      nextJs,
      mui,
      'stripe',
      typeScript,
      restfulApi,
      redux,
      'sendgrid',
      'firebase',
      reactJs,
      js,
    ],
  },
  {
    portfolioTitle: 'ACME Fantasy Football League',
    img: [
      '/portfolio/acme/portfolio-03.jpg',
      '/portfolio/acme/portfolio-01.jpg',
      '/portfolio/acme/portfolio-02.jpg',
    ],
    description: '',
    usedTechs: [
      nextJs,
      tailwindCss,
      typeScript,
      'stripe',
      restfulApi,
      'firebase',
      'socket.io',
      redux,
      reactJs,
      js,
    ],
  },
  {
    portfolioTitle: 'Erzy',
    img: [
      '/portfolio/erzy/portfolio-02.jpg',
      '/portfolio/erzy/portfolio-01.jpg',
      '/portfolio/erzy/portfolio-03.jpg',
    ],
    description: '',
    usedTechs: [
      nextJs,
      styledComponent,
      sass,
      typeScript,
      restfulApi,
      redux,
      reactJs,
      js,
    ],
  },
  {
    portfolioTitle: 'Lize Transport',
    img: [
      '/portfolio/lize/portfolio-03.jpg',
      '/portfolio/lize/portfolio-01.jpg',
      '/portfolio/lize/portfolio-02.jpg',
    ],
    description: '',
    usedTechs: [
      nextJs,
      tailwindCss,
      'sendgrid',
      'twilio',
      typeScript,
      restfulApi,
      redux,
      reactJs,
      js,
    ],
  },

  {
    portfolioTitle: 'DimuaDi',
    img: [
      '/portfolio/lize/portfolio-01.jpg',
      '/portfolio/lize/portfolio-02.jpg',
      '/portfolio/lize/portfolio-03.jpg',
    ],
    description: '',
    usedTechs: [
      nextJs,
      tailwindCss,
      'stripe',
      typeScript,
      graphQl,
      redux,
      reactJs,
      js,
    ],
  },
  {
    portfolioTitle: 'Gigaland',
    img: [
      '/portfolio/lize/portfolio-02.jpg',
      '/portfolio/lize/portfolio-01.jpg',
      '/portfolio/lize/portfolio-03.jpg',
    ],
    description: '',
    usedTechs: [nextJs, mui, typeScript, graphQl, redux, reactJs, js],
  },
];

