import { portfolioItem } from '../types';

export const portfolioArr: portfolioItem[] = [
  {
    portfolioTitle: 'Uptechunt',
    projectUrl: 'https://uptechunt.com/',
    img: [
      '/portfolio/uptechunt/portfolio-02.jpg',
      '/portfolio/uptechunt/portfolio-01.jpg',
      '/portfolio/uptechunt/portfolio-03.jpg',
    ],
    description: '',
    usedTechs: [
      'Next.js',
      'Material UI',
      'stripe',
      'TypeScript',
      'REST API',
      'Redux',
      'sendgrid',
      'firebase',
      'React.js',
      'JavaScript',
    ],
  },
  {
    portfolioTitle: 'WithJoy',
    projectUrl: 'https://withjoy.com/',
    img: [
      '/portfolio/withjoy/portfolio-01.jpg',
      '/portfolio/withjoy/portfolio-02.jpg',
      '/portfolio/withjoy/portfolio-03.jpg',
    ],
    description: '',
    usedTechs: [
      'Next.js',
      'Tailwind CSS',
      'react spring',
      'zustand',
      'stripe',
      'TypeScript',
      'GraphQL',
      'React.js',
      'JavaScript',
    ],
  },
  {
    portfolioTitle: 'ACME Fantasy Football League',
    projectUrl: 'https://acmerealfantasyfootball.com/',
    img: [
      '/portfolio/acme/portfolio-03.jpg',
      '/portfolio/acme/portfolio-01.jpg',
      '/portfolio/acme/portfolio-02.jpg',
    ],
    description: '',
    usedTechs: [
      'Next.js',
      'Tailwind CSS',
      'TypeScript',
      'stripe',
      'REST API',
      'firebase',
      'socket.io',
      'Redux',
      'React.js',
      'JavaScript',
    ],
  },
  {
    portfolioTitle: 'Erzy',
    projectUrl: 'https://erzy.net/',
    img: [
      '/portfolio/erzy/portfolio-02.jpg',
      '/portfolio/erzy/portfolio-01.jpg',
      '/portfolio/erzy/portfolio-03.jpg',
    ],
    description: '',
    usedTechs: [
      'Next.js',
      'Styled Component',
      'Sass',
      'TypeScript',
      'REST API',
      'Redux',
      'React.js',
      'JavaScript',
    ],
  },
  {
    portfolioTitle: 'Lize Transport',
    projectUrl: 'https://lizetransport.com/',
    img: [
      '/portfolio/lize/portfolio-03.jpg',
      '/portfolio/lize/portfolio-01.jpg',
      '/portfolio/lize/portfolio-02.jpg',
    ],
    description: '',
    usedTechs: [
      'Next.js',
      'Tailwind CSS',
      'sendgrid',
      'twilio',
      'TypeScript',
      'REST API',
      'Redux',
      'React.js',
      'JavaScript',
    ],
  },

  {
    portfolioTitle: 'DimuaDi',
    projectUrl: 'https://ecommerce.devfirmltd.com/',
    img: [
      '/portfolio/lize/portfolio-01.jpg',
      '/portfolio/lize/portfolio-02.jpg',
      '/portfolio/lize/portfolio-03.jpg',
    ],
    description: '',
    usedTechs: [
      'Next.js',
      'Tailwind CSS',
      'stripe',
      'TypeScript',
      'GraphQL',
      'Redux',
      'React.js',
      'JavaScript',
    ],
  },
  {
    portfolioTitle: 'Gigaland',
    projectUrl: 'https://devfirm-nft.web.app/',
    img: [
      '/portfolio/lize/portfolio-02.jpg',
      '/portfolio/lize/portfolio-01.jpg',
      '/portfolio/lize/portfolio-03.jpg',
    ],
    description: '',
    usedTechs: [
      'Next.js',
      'Material UI',
      'TypeScript',
      'GraphQL',
      'Redux',
      'React.js',
      'JavaScript',
    ],
  },
];

